export const embossPresets = [
  {
    turbType: "turbulence",
    turbFreqX: 0.001,
    turbFreqY: 0.001,
    turbOct: 1,
    turbBlur: 2,
    dispScale: 200,
    specConstant: 0.75,
    specExponent: 30,
    surfaceScale: 5,
    pointX: -50,
    pointY: -100,
    pointZ: 400,
    lightColor: "#ffffff",
    opacity: 1,
    blurX: 2,
    blurY: 2,
  },
];
