export const embossPresets = [
  {
    fractalNoise: true,
    turbFreqX: 1,
    turbFreqY: 1,
    turbOct: 1,
    turbBlur: 20,
    dispScale: 200,
    specConstant: 8,
    specExponent: 30,
    surfaceScale: 5,
    pointX: -50,
    pointY: -100,
    pointZ: 400,
    lightColor: "#ffffff",
    opacity: 1,
    blurX: 2,
    blurY: 2,
  },
];
