import { StoneSettings } from "../SvgTemplate";

const stoneList: StoneSettings[] = [
  {
    turbType: "turbulence",
    turbFreqX: 2,
    turbFreqY: 1,
    turbOct: 3,
    redAmp: 90,
    redExp: 15,
    redOff: -69,
    greenAmp: 66,
    greenExp: -24,
    greenOff: -23,
    blueAmp: 11,
    blueExp: -85,
    blueOff: -16,
    rotation: 298,
  },
  {
    turbType: "fractalNoise",
    turbFreqX: 4,
    turbFreqY: 7,
    turbOct: 2,
    redAmp: 69,
    redExp: -43,
    redOff: 16,
    greenAmp: 61,
    greenExp: -66,
    greenOff: -63,
    blueAmp: 58,
    blueExp: 1,
    blueOff: -15,
    rotation: 26,
  },
  {
    turbType: "turbulence",
    turbFreqX: 8,
    turbFreqY: 7,
    turbOct: 3,
    redAmp: 60,
    redExp: -56,
    redOff: -48,
    greenAmp: 74,
    greenExp: -52,
    greenOff: -36,
    blueAmp: 78,
    blueExp: 48,
    blueOff: 46,
    rotation: 123,
  },
  {
    turbType: "turbulence",
    turbFreqX: 6,
    turbFreqY: 3,
    turbOct: 3,
    redAmp: -32,
    redExp: -39,
    redOff: -48,
    greenAmp: 42,
    greenExp: -36,
    greenOff: -19,
    blueAmp: 39,
    blueExp: 18,
    blueOff: 12,
    rotation: 123,
  },
  {
    turbType: "turbulence",
    turbFreqX: 6,
    turbFreqY: 3,
    turbOct: 3,
    redAmp: 14,
    redExp: -70,
    redOff: -12,
    greenAmp: 29,
    greenExp: -92,
    greenOff: -38,
    blueAmp: 79,
    blueExp: -72,
    blueOff: -63,
    rotation: 30,
  },
  {
    turbType: "fractalNoise",
    turbFreqX: 17,
    turbFreqY: 9,
    turbOct: 3,
    redAmp: 64,
    redExp: -76,
    redOff: -10,
    greenAmp: -13,
    greenExp: -88,
    greenOff: 63,
    blueAmp: 57,
    blueExp: -99,
    blueOff: 1,
    rotation: 270,
  },
  {
    turbType: "turbulence",
    turbFreqX: 2,
    turbFreqY: 2,
    turbOct: 3,
    redAmp: 12,
    redExp: 30,
    redOff: 9,
    greenAmp: -16,
    greenExp: -88,
    greenOff: 71,
    blueAmp: 58,
    blueExp: -39,
    blueOff: 76,
    rotation: 296,
  },
  {
    turbType: "fractalNoise",
    turbFreqX: 34,
    turbFreqY: 6,
    turbOct: 3,
    redAmp: 17,
    redExp: -18,
    redOff: 91,
    greenAmp: 50,
    greenExp: -44,
    greenOff: -21,
    blueAmp: 58,
    blueExp: -82,
    blueOff: -36,
    rotation: 155,
  },
  {
    turbType: "fractalNoise",
    turbFreqX: 8,
    turbFreqY: 2,
    turbOct: 1,
    redAmp: 34,
    redExp: -31,
    redOff: 29,
    greenAmp: 56,
    greenExp: -57,
    greenOff: -82,
    blueAmp: 68,
    blueExp: 51,
    blueOff: -80,
    rotation: 15,
  },
  {
    turbType: "turbulence",
    turbFreqX: 7,
    turbFreqY: 2,
    turbOct: 2,
    redAmp: 8,
    redExp: 14,
    redOff: 3,
    greenAmp: 64,
    greenExp: -42,
    greenOff: -68,
    blueAmp: 99,
    blueExp: 100,
    blueOff: 17,
    rotation: 149,
  },
  {
    turbType: "fractalNoise",
    turbFreqX: 6,
    turbFreqY: 2,
    turbOct: 3,
    redAmp: 43,
    redExp: -66,
    redOff: 12,
    greenAmp: 100,
    greenExp: 93,
    greenOff: -33,
    blueAmp: 100,
    blueExp: 86,
    blueOff: -26,
    rotation: 24,
  },
  {
    turbType: "fractalNoise",
    turbFreqX: 3,
    turbFreqY: 5,
    turbOct: 5,
    redAmp: -2,
    redExp: -76,
    redOff: 31,
    greenAmp: 72,
    greenExp: 80,
    greenOff: -32,
    blueAmp: 92,
    blueExp: 79,
    blueOff: 67,
    rotation: 117,
  },
  {
    turbType: "fractalNoise",
    turbFreqX: 2,
    turbFreqY: 6,
    turbOct: 5,
    redAmp: 0,
    redExp: -76,
    redOff: 47,
    greenAmp: 81,
    greenExp: 30,
    greenOff: -54,
    blueAmp: -60,
    blueExp: 79,
    blueOff: 36,
    rotation: 227,
  },
  {
    turbType: "turbulence",
    turbFreqX: 2,
    turbFreqY: 4,
    turbOct: 3,
    redAmp: 30,
    redExp: -74,
    redOff: -56,
    greenAmp: 62,
    greenExp: -52,
    greenOff: -68,
    blueAmp: 12,
    blueExp: -32,
    blueOff: -6,
    rotation: 101,
  },
  {
    turbType: "turbulence",
    turbFreqX: 0,
    turbFreqY: 4,
    turbOct: 3,
    redAmp: 9,
    redExp: -100,
    redOff: 30,
    greenAmp: 5,
    greenExp: -98,
    greenOff: 64,
    blueAmp: 41,
    blueExp: -65,
    blueOff: -79,
    rotation: 136,
  },
  {
    turbType: "turbulence",
    turbFreqX: 16,
    turbFreqY: 9,
    turbOct: 3,
    redAmp: -44,
    redExp: 78,
    redOff: -22,
    greenAmp: 54,
    greenExp: 72,
    greenOff: 5,
    blueAmp: 57,
    blueExp: 71,
    blueOff: -4,
    rotation: 49,
  },
  {
    turbType: "fractalNoise",
    turbFreqX: 7,
    turbFreqY: 5,
    turbOct: 3,
    redAmp: 66,
    redExp: 86,
    redOff: -28,
    greenAmp: -9,
    greenExp: -77,
    greenOff: -4,
    blueAmp: 30,
    blueExp: 5,
    blueOff: -16,
    rotation: 115,
  },
  {
    turbType: "fractalNoise",
    turbFreqX: 5,
    turbFreqY: 4,
    turbOct: 4,
    redAmp: 40,
    redExp: -51,
    redOff: -61,
    greenAmp: -19,
    greenExp: -77,
    greenOff: 42,
    blueAmp: -64,
    blueExp: 6,
    blueOff: 76,
    rotation: 322,
  },
  {
    turbType: "turbulence",
    turbFreqX: 5,
    turbFreqY: 3,
    turbOct: 1,
    redAmp: 79,
    redExp: -51,
    redOff: -61,
    greenAmp: -12,
    greenExp: -77,
    greenOff: 51,
    blueAmp: 45,
    blueExp: 100,
    blueOff: 14,
    rotation: 166,
  },
  {
    turbType: "turbulence",
    turbFreqX: 2,
    turbFreqY: 2,
    turbOct: 1,
    redAmp: 33,
    redExp: -51,
    redOff: -90,
    greenAmp: -23,
    greenExp: -96,
    greenOff: 35,
    blueAmp: 47,
    blueExp: -51,
    blueOff: 82,
    rotation: 123,
  },
  {
    turbType: "turbulence",
    turbFreqX: 3,
    turbFreqY: 3,
    turbOct: 6,
    redAmp: 48,
    redExp: -71,
    redOff: -90,
    greenAmp: 26,
    greenExp: -60,
    greenOff: -31,
    blueAmp: -87,
    blueExp: -87,
    blueOff: -89,
    rotation: 123,
  },
  {
    turbType: "turbulence",
    turbFreqX: 3,
    turbFreqY: 9,
    turbOct: 2,
    redAmp: 100,
    redExp: 1,
    redOff: -11,
    greenAmp: 41,
    greenExp: -93,
    greenOff: -96,
    blueAmp: 33,
    blueExp: -88,
    blueOff: -100,
    rotation: 123,
  },
  {
    turbType: "fractalNoise",
    turbFreqX: 4,
    turbFreqY: 4,
    turbOct: 7,
    redAmp: 39,
    redExp: -100,
    redOff: -39,
    greenAmp: 38,
    greenExp: -52,
    greenOff: -53,
    blueAmp: 32,
    blueExp: -93,
    blueOff: 48,
    rotation: 82,
  },
  {
    turbType: "turbulence",
    turbFreqX: 7,
    turbFreqY: 6,
    turbOct: 1,
    redAmp: 4,
    redExp: -57,
    redOff: -9,
    greenAmp: -51,
    greenExp: -12,
    greenOff: 51,
    blueAmp: 24,
    blueExp: -83,
    blueOff: -80,
    rotation: 111,
  },
];

export default stoneList;
