// SPDX-License-Identifier: LGPL-3.0-only
pragma solidity ^0.8.6;

library InceptionStones {
  struct Stone {
    string name;
    bool fractalNoise;
    uint8 turbFreqX;
    uint8 turbFreqY;
    uint8 turbOct;
    int8 redAmp;
    int8 redExp;
    int8 redOff;
    int8 greenAmp;
    int8 greenExp;
    int8 greenOff;
    int8 blueAmp;
    int8 blueExp;
    int8 blueOff;
    uint16 rotation;
  }

  function list() external pure returns (Stone[29] memory) {
    return [
      Stone({
        name: "Tyrolite",
        fractalNoise: false,
        turbFreqX: 2,
        turbFreqY: 1,
        turbOct: 3,
        redAmp: 90,
        redExp: 15,
        redOff: -69,
        greenAmp: 66,
        greenExp: -24,
        greenOff: -23,
        blueAmp: 11,
        blueExp: -85,
        blueOff: -16,
        rotation: 218
      }),
      Stone({
        name: "Sugilite",
        fractalNoise: false,
        turbFreqX: 2,
        turbFreqY: 2,
        turbOct: 3,
        redAmp: 12,
        redExp: 30,
        redOff: 9,
        greenAmp: -16,
        greenExp: -88,
        greenOff: 71,
        blueAmp: 58,
        blueExp: -39,
        blueOff: 76,
        rotation: 216
      }),
      Stone({
        name: "Uranospinite",
        fractalNoise: false,
        turbFreqX: 2,
        turbFreqY: 4,
        turbOct: 3,
        redAmp: 30,
        redExp: -74,
        redOff: -56,
        greenAmp: 62,
        greenExp: -52,
        greenOff: -68,
        blueAmp: 12,
        blueExp: -32,
        blueOff: -6,
        rotation: 21
      }),
      Stone({
        name: "Viseite",
        fractalNoise: false,
        turbFreqX: 8,
        turbFreqY: 7,
        turbOct: 3,
        redAmp: 60,
        redExp: -56,
        redOff: -48,
        greenAmp: 74,
        greenExp: -52,
        greenOff: -36,
        blueAmp: 78,
        blueExp: 48,
        blueOff: 46,
        rotation: 43
      }),
      Stone({
        name: "Langite",
        fractalNoise: false,
        turbFreqX: 6,
        turbFreqY: 3,
        turbOct: 3,
        redAmp: -32,
        redExp: -39,
        redOff: -48,
        greenAmp: 42,
        greenExp: -36,
        greenOff: -19,
        blueAmp: 39,
        blueExp: 18,
        blueOff: 12,
        rotation: 43
      }),
      Stone({
        name: "Lepidolite",
        fractalNoise: false,
        turbFreqX: 6,
        turbFreqY: 3,
        turbOct: 3,
        redAmp: 14,
        redExp: -70,
        redOff: -12,
        greenAmp: 29,
        greenExp: -92,
        greenOff: -38,
        blueAmp: 79,
        blueExp: -72,
        blueOff: -63,
        rotation: 310
      }),
      Stone({
        name: "Huemulite",
        fractalNoise: false,
        turbFreqX: 2,
        turbFreqY: 2,
        turbOct: 3,
        redAmp: 72,
        redExp: -92,
        redOff: -34,
        greenAmp: -43,
        greenExp: -30,
        greenOff: 78,
        blueAmp: -75,
        blueExp: -39,
        blueOff: 76,
        rotation: 114
      }),
      Stone({
        name: "Bunsenite",
        fractalNoise: false,
        turbFreqX: 0,
        turbFreqY: 4,
        turbOct: 3,
        redAmp: 9,
        redExp: -100,
        redOff: 30,
        greenAmp: 5,
        greenExp: -98,
        greenOff: 64,
        blueAmp: 41,
        blueExp: -65,
        blueOff: -79,
        rotation: 56
      }),
      Stone({
        name: "Serandite",
        fractalNoise: false,
        turbFreqX: 5,
        turbFreqY: 3,
        turbOct: 1,
        redAmp: 79,
        redExp: -51,
        redOff: -61,
        greenAmp: -12,
        greenExp: -77,
        greenOff: 51,
        blueAmp: 45,
        blueExp: 100,
        blueOff: 14,
        rotation: 86
      }),
      Stone({
        name: "Petterdite",
        fractalNoise: false,
        turbFreqX: 2,
        turbFreqY: 2,
        turbOct: 1,
        redAmp: 33,
        redExp: -51,
        redOff: -90,
        greenAmp: -23,
        greenExp: -96,
        greenOff: 35,
        blueAmp: 47,
        blueExp: -51,
        blueOff: 82,
        rotation: 43
      }),
      Stone({
        name: "Bottinoite",
        fractalNoise: false,
        turbFreqX: 7,
        turbFreqY: 2,
        turbOct: 2,
        redAmp: 8,
        redExp: 14,
        redOff: 3,
        greenAmp: 64,
        greenExp: -42,
        greenOff: -68,
        blueAmp: 99,
        blueExp: 100,
        blueOff: 17,
        rotation: 69
      }),
      Stone({
        name: "Augelite",
        fractalNoise: false,
        turbFreqX: 3,
        turbFreqY: 3,
        turbOct: 6,
        redAmp: 48,
        redExp: -71,
        redOff: -90,
        greenAmp: 26,
        greenExp: -60,
        greenOff: -31,
        blueAmp: -87,
        blueExp: -87,
        blueOff: -89,
        rotation: 43
      }),
      Stone({
        name: "Pascoite",
        fractalNoise: false,
        turbFreqX: 1,
        turbFreqY: 4,
        turbOct: 4,
        redAmp: 77,
        redExp: -100,
        redOff: 55,
        greenAmp: 9,
        greenExp: -97,
        greenOff: -4,
        blueAmp: -10,
        blueExp: -65,
        blueOff: -81,
        rotation: 244
      }),
      Stone({
        name: "Jarosite",
        fractalNoise: false,
        turbFreqX: 3,
        turbFreqY: 9,
        turbOct: 2,
        redAmp: 100,
        redExp: 1,
        redOff: -11,
        greenAmp: 41,
        greenExp: -93,
        greenOff: -96,
        blueAmp: 33,
        blueExp: -88,
        blueOff: -100,
        rotation: 43
      }),
      Stone({
        name: "Pollucite",
        fractalNoise: true,
        turbFreqX: 4,
        turbFreqY: 7,
        turbOct: 2,
        redAmp: 69,
        redExp: -43,
        redOff: 16,
        greenAmp: 61,
        greenExp: -66,
        greenOff: -63,
        blueAmp: 58,
        blueExp: 1,
        blueOff: -15,
        rotation: 306
      }),
      Stone({
        name: "Andradite",
        fractalNoise: false,
        turbFreqX: 16,
        turbFreqY: 9,
        turbOct: 3,
        redAmp: -44,
        redExp: 78,
        redOff: -22,
        greenAmp: 54,
        greenExp: 72,
        greenOff: 5,
        blueAmp: 57,
        blueExp: 71,
        blueOff: -4,
        rotation: 329
      }),
      Stone({
        name: "Allactite",
        fractalNoise: false,
        turbFreqX: 7,
        turbFreqY: 6,
        turbOct: 1,
        redAmp: 4,
        redExp: -57,
        redOff: -9,
        greenAmp: -51,
        greenExp: -12,
        greenOff: 51,
        blueAmp: 24,
        blueExp: -83,
        blueOff: -80,
        rotation: 31
      }),
      Stone({
        name: "Borcarite",
        fractalNoise: false,
        turbFreqX: 4,
        turbFreqY: 0,
        turbOct: 3,
        redAmp: -2,
        redExp: -94,
        redOff: -22,
        greenAmp: 19,
        greenExp: -79,
        greenOff: 18,
        blueAmp: 42,
        blueExp: -61,
        blueOff: -70,
        rotation: 56
      }),
      Stone({
        name: "Jouravskite",
        fractalNoise: false,
        turbFreqX: 1,
        turbFreqY: 4,
        turbOct: 4,
        redAmp: 46,
        redExp: -98,
        redOff: -87,
        greenAmp: 39,
        greenExp: -61,
        greenOff: -39,
        blueAmp: -30,
        blueExp: -32,
        blueOff: -6,
        rotation: 48
      }),
      Stone({
        name: "Murmanite",
        fractalNoise: true,
        turbFreqX: 34,
        turbFreqY: 6,
        turbOct: 3,
        redAmp: 17,
        redExp: -18,
        redOff: 91,
        greenAmp: 50,
        greenExp: -44,
        greenOff: -21,
        blueAmp: 58,
        blueExp: -82,
        blueOff: -36,
        rotation: 75
      }),
      Stone({
        name: "Kasolite",
        fractalNoise: true,
        turbFreqX: 8,
        turbFreqY: 2,
        turbOct: 1,
        redAmp: 34,
        redExp: -31,
        redOff: 29,
        greenAmp: 56,
        greenExp: -57,
        greenOff: -82,
        blueAmp: 68,
        blueExp: 51,
        blueOff: -80,
        rotation: 295
      }),
      Stone({
        name: "Olmiite",
        fractalNoise: true,
        turbFreqX: 6,
        turbFreqY: 2,
        turbOct: 3,
        redAmp: 43,
        redExp: -66,
        redOff: 12,
        greenAmp: 100,
        greenExp: 93,
        greenOff: -33,
        blueAmp: 100,
        blueExp: 86,
        blueOff: -26,
        rotation: 304
      }),
      Stone({
        name: "Ussingite",
        fractalNoise: true,
        turbFreqX: 3,
        turbFreqY: 5,
        turbOct: 5,
        redAmp: -2,
        redExp: -76,
        redOff: 31,
        greenAmp: 72,
        greenExp: 80,
        greenOff: -32,
        blueAmp: 92,
        blueExp: 79,
        blueOff: 67,
        rotation: 37
      }),
      Stone({
        name: "Haiweeite",
        fractalNoise: true,
        turbFreqX: 2,
        turbFreqY: 6,
        turbOct: 5,
        redAmp: 0,
        redExp: -76,
        redOff: 47,
        greenAmp: 81,
        greenExp: 30,
        greenOff: -54,
        blueAmp: -60,
        blueExp: 79,
        blueOff: 36,
        rotation: 147
      }),
      Stone({
        name: "Hematite",
        fractalNoise: true,
        turbFreqX: 7,
        turbFreqY: 5,
        turbOct: 3,
        redAmp: 66,
        redExp: 86,
        redOff: -28,
        greenAmp: -9,
        greenExp: -77,
        greenOff: -4,
        blueAmp: 30,
        blueExp: 5,
        blueOff: -16,
        rotation: 35
      }),
      Stone({
        name: "Dioptase",
        fractalNoise: true,
        turbFreqX: 5,
        turbFreqY: 4,
        turbOct: 4,
        redAmp: 40,
        redExp: -51,
        redOff: -61,
        greenAmp: -19,
        greenExp: -77,
        greenOff: 42,
        blueAmp: -64,
        blueExp: 6,
        blueOff: 76,
        rotation: 242
      }),
      Stone({
        name: "Ekaterinite",
        fractalNoise: true,
        turbFreqX: 17,
        turbFreqY: 9,
        turbOct: 3,
        redAmp: 64,
        redExp: -76,
        redOff: -10,
        greenAmp: -13,
        greenExp: -88,
        greenOff: 63,
        blueAmp: 57,
        blueExp: -99,
        blueOff: 1,
        rotation: 190
      }),
      Stone({
        name: "Purpurite",
        fractalNoise: true,
        turbFreqX: 4,
        turbFreqY: 4,
        turbOct: 7,
        redAmp: 39,
        redExp: -100,
        redOff: -39,
        greenAmp: 38,
        greenExp: -52,
        greenOff: -53,
        blueAmp: 32,
        blueExp: -93,
        blueOff: 48,
        rotation: 2
      }),
      Stone({
        name: "Zdenekite",
        fractalNoise: true,
        turbFreqX: 4,
        turbFreqY: 9,
        turbOct: 3,
        redAmp: -59,
        redExp: -76,
        redOff: -10,
        greenAmp: 18,
        greenExp: -88,
        greenOff: 4,
        blueAmp: 66,
        blueExp: -99,
        blueOff: -52,
        rotation: 111
      })
    ];
  }
}
