export const presets = [
  {
    specConstant: 6.78,
    specExponent: -200,
    surfaceScale: -200,
    pointX: 242,
    pointY: -4354,
    pointZ: 2000,
    lightColor: "#ffffff",
    opacity: 1,
    blurX: 13.841,
    blurY: 50,
    pointsAtX: 0,
    pointsAtY: 0,
    pointsAtZ: 0,
    limitingConeAngle: 15,
    lightType: "point",
  },
  {
    specConstant: 9.72,
    specExponent: 198.4,
    surfaceScale: -200,
    pointX: 3247,
    pointY: -187,
    pointZ: 4315,
    lightColor: "#ffffff",
    opacity: 1,
    blurX: 2.196,
    blurY: 0,
    pointsAtX: 0,
    pointsAtY: 0,
    pointsAtZ: 0,
    limitingConeAngle: 15,
    lightType: "point",
  },
  {
    specConstant: 26.82,
    specExponent: 20,
    surfaceScale: -94.9,
    pointX: -579,
    pointY: 1399,
    pointZ: 1291,
    lightColor: "#ffffff",
    opacity: 1,
    blurX: 0,
    blurY: 0,
    pointsAtX: 0,
    pointsAtY: 0,
    pointsAtZ: 0,
    limitingConeAngle: 15,
    lightType: "point",
  },
];
