export const embossPresets = [
  {
    blurX: 19,
    blurY: 17,
    dispScale: 77,
    lightColor: { hue: 0, saturation: 0, lightness: 100 },
    opacity: 20,
    pointX: -493,
    pointY: 514,
    pointZ: 104,
    specConstant: 819,
    specExponent: 4,
    surfaceScale: -7,
    turbBlur: 54,
    turbFreqX: 17,
    turbFreqY: 17,
    turbOct: 1,
    fractalNoise: true,
  },
  {
    blurX: 19,
    blurY: 17,
    dispScale: 90,
    lightColor: { hue: 0, saturation: 0, lightness: 100 },
    opacity: 25,
    pointX: -139,
    pointY: 514,
    pointZ: 104,
    specConstant: 762,
    specExponent: 4,
    surfaceScale: -11,
    turbBlur: 76,
    turbFreqX: 1,
    turbFreqY: 9,
    turbOct: 1,
    fractalNoise: true,
  },
  {
    blurX: 19,
    blurY: 17,
    dispScale: 88,
    lightColor: { hue: 58, saturation: 100, lightness: 94 },
    opacity: 34,
    pointX: -493,
    pointY: 514,
    pointZ: 104,
    specConstant: 359,
    specExponent: 3,
    surfaceScale: 157,
    turbBlur: 73,
    turbFreqX: 19,
    turbFreqY: 19,
    turbOct: 1,
    fractalNoise: true,
  },
];
